import 'dart:io';

import 'package:app/core/errors/failures.dart';
import 'package:app/features/post/domain/entities/post.dart';
import 'package:app/features/post/domain/entities/post_enums.dart';
import 'package:app/features/post/domain/repositories/post_repository.dart';
import 'package:dartz/dartz.dart';
import 'package:equatable/equatable.dart';

class CreatePostUseCase {
  final PostRepository repository;
  CreatePostUseCase(this.repository);

  Future<Either<Failure, Post>> call(CreatePostParams params) async {
    // Validate required parameters
    if (params.organizationId.trim().isEmpty) {
      return const Left(ValidationFailure('Organization ID is required'));
    }

    if (params.title.trim().isEmpty) {
      return const Left(ValidationFailure('Event title is required'));
    }

    if (params.createdBy.trim().isEmpty) {
      return const Left(ValidationFailure('User ID is required'));
    }

    // Check user permissions
    final permissionResult = await repository.canCreatePost(
      params.createdBy,
      params.organizationId,
    );

    if (permissionResult.isLeft()) {
      return permissionResult.fold(
        (failure) => Left(failure),
        (_) => throw Exception('Unexpected permission result'),
      );
    }

    final canCreate = permissionResult.fold(
      (_) => false,
      (canCreate) => canCreate,
    );

    if (!canCreate) {
      return const Left(
        PermissionFailure('Insufficient permissions to create posts'),
      );
    }

    // Validate YouTube URL if provided
    if (params.youtubeUrl != null && params.youtubeUrl!.isNotEmpty) {
      if (!_isValidYoutubeUrl(params.youtubeUrl!)) {
        return const Left(ValidationFailure('Invalid YouTube URL format'));
      }
    }

    String? primaryImageUrl = params.primaryImageUrl;
    if (params.primaryImageFile != null) {
      final uploadResult = await repository.uploadImage(
        params.primaryImageFile!,
        params.organizationId,
        'primary_image', // primary_image postId before creation (backend may not need it)
      );

      if (uploadResult.isLeft()) {
        return uploadResult.fold(
          (failure) => Left(failure),
          (_) => throw Exception('Unexpected upload result'),
        );
      }

      primaryImageUrl = uploadResult.getOrElse(() => '');
    }

    // Create post entity
    final now = DateTime.now();
    final post = Post(
      id: '', // Will be generated by the backend
      organizationId: params.organizationId.trim(),
      title: params.title.trim(),
      description: params.description.trim(),
      primaryImageUrl: primaryImageUrl,
      price: params.price,
      area: params.area,
      capacity: params.capacity,
      roomType: params.roomType,
      amenities: params.amenities ?? const [],
      tags: params.tags ?? const [],
      status: params.status ?? PostStatus.available, // default if needed
      longitude: params.longitude,
      latitude: params.latitude,
      youtubeUrl: params.youtubeUrl?.trim(),
      additionalImages: const [], // will be set after image upload
      createdBy: params.createdBy.trim(),
      updatedBy: params.updatedBy.trim(),
      createdAt: now,
      updatedAt: now,
    );

    // Create post with images
    return await repository.createPost(post, params.additionalImages);
  }

  /// Validate YouTube URL format
  bool _isValidYoutubeUrl(String url) {
    try {
      final uri = Uri.parse(url);
      return (uri.host.contains('youtube.com') ||
              uri.host.contains('youtu.be')) &&
          uri.hasScheme &&
          (uri.scheme == 'http' || uri.scheme == 'https');
    } catch (e) {
      return false;
    }
  }
}

class CreatePostParams extends Equatable {
  final String organizationId;
  final String title;
  final String description;
  final String primaryImageUrl;
  final File? primaryImageFile;
  final List<File> additionalImages;
  final String? youtubeUrl;
  final double? longitude;
  final double? latitude;
  final double price;
  final double? area;
  final int? capacity;
  final RoomType? roomType;
  final List<AmenityType>? amenities;
  final List<PostTag>? tags;
  final PostStatus? status;
  final String createdBy;
  final String updatedBy;

  const CreatePostParams({
    required this.organizationId,
    required this.title,
    required this.description,
    required this.primaryImageUrl,
    this.primaryImageFile,
    this.additionalImages = const [],
    this.youtubeUrl,
    this.longitude,
    this.latitude,
    required this.price,
    this.area,
    this.capacity,
    this.roomType,
    this.amenities,
    this.tags,
    this.status,
    required this.createdBy,
    required this.updatedBy,
  });

  @override
  List<Object?> get props => [
    organizationId,
    title,
    description,
    primaryImageUrl,
    additionalImages,
    youtubeUrl,
    longitude,
    latitude,
    price,
    area,
    capacity,
    roomType,
    amenities,
    tags,
    status,
    createdBy,
    updatedBy,
  ];

  // Create a copy with updated parameters
  CreatePostParams copyWith({
    String? organizationId,
    String? title,
    String? description,
    String? primaryImageUrl,
    List<File>? additionalImages,
    String? youtubeUrl,
    double? longitude,
    double? latitude,
    double? price,
    double? area,
    int? capacity,
    RoomType? roomType,
    List<AmenityType>? amenities,
    List<PostTag>? tags,
    PostStatus? status,
    String? createdBy,
    String? updatedBy,
  }) {
    return CreatePostParams(
      organizationId: organizationId ?? this.organizationId,
      title: title ?? this.title,
      description: description ?? this.description,
      primaryImageUrl: primaryImageUrl ?? this.primaryImageUrl,
      primaryImageFile: primaryImageFile ?? primaryImageFile,
      additionalImages: additionalImages ?? this.additionalImages,
      youtubeUrl: youtubeUrl ?? this.youtubeUrl,
      longitude: longitude ?? this.longitude,
      latitude: latitude ?? this.latitude,
      price: price ?? this.price,
      area: area ?? this.area,
      capacity: capacity ?? this.capacity,
      roomType: roomType ?? this.roomType,
      amenities: amenities ?? this.amenities,
      tags: tags ?? this.tags,
      status: status ?? this.status,
      createdBy: createdBy ?? this.createdBy,
      updatedBy: updatedBy ?? this.updatedBy,
    );
  }

  /// Validate parameters
  List<String> validate() {
    final errors = <String>[];

    // Required basic fields
    if (organizationId.trim().isEmpty) {
      errors.add('Organization ID is required');
    }

    if (title.trim().isEmpty) {
      errors.add('Title is required');
    }

    if (description.trim().isEmpty) {
      errors.add('Description is required');
    }

    // Price (required in ctor) must be positive
    if (price <= 0) {
      errors.add('Price must be greater than 0');
    }

    // Area if provided must be non-negative
    if (area != null && area! < 0) {
      errors.add('Area must be 0 or greater');
    }

    // Capacity if provided must be positive integer
    if (capacity != null && capacity! <= 0) {
      errors.add('Capacity must be greater than 0');
    }

    // Latitude/Longitude: either both provided or neither
    if ((latitude == null) ^ (longitude == null)) {
      errors.add('Both latitude and longitude must be provided together');
    } else if (latitude != null && longitude != null) {
      if (latitude! < -90.0 || latitude! > 90.0) {
        errors.add('Latitude must be between -90 and 90');
      }
      if (longitude! < -180.0 || longitude! > 180.0) {
        errors.add('Longitude must be between -180 and 180');
      }
    }

    // YouTube URL validation (if provided)
    if (youtubeUrl != null && youtubeUrl!.isNotEmpty) {
      try {
        final uri = Uri.parse(youtubeUrl!);
        final host = uri.host.toLowerCase();
        if (!(host.contains('youtube.com') || host.contains('youtu.be')) ||
            !uri.hasScheme ||
            !(uri.scheme == 'http' || uri.scheme == 'https')) {
          errors.add('Invalid YouTube URL format');
        }
      } catch (e) {
        errors.add('Invalid YouTube URL format');
      }
    }

    // createdBy / updatedBy must be present (they are required in ctor but double-check)
    if (createdBy.trim().isEmpty) {
      errors.add('createdBy is required');
    }
    if (updatedBy.trim().isEmpty) {
      errors.add('updatedBy is required');
    }

    // Optional: roomType, amenities, tags, status - no strict validation here
    // but you can add domain-specific checks later if needed.

    return errors;
  }

  /// Check if parameters are valid
  bool get isValid => validate().isEmpty;
}
